owner: caliza-financial 
repo: caliza-status 

sites:
  - name: API
    url: https://api.caliza.com/core-api/actuator
  - name: Dashboard
    url: https://dashboard.caliza.com

assignees:
  - leonardocaliza
  - marcusmc
  
status-website: 
  cname: status.caliza.com
  logoUrl: https://raw.githubusercontent.com/Caliza-Financial/caliza-status/refs/heads/master/assets/caliza-dark-logo.svg
  name: Caliza Status
  introTitle: "Caliza system status"
  introMessage: >
    Public monitoring for the **API** and **Dashboard**. Data updates automatically every 5 minutes.
  navbar:
    - title: Status
      href: /
    - title: Incidents
      href: https://github.com/$OWNER/$REPO/issues
    - title: API Docs
      href: https://docs.caliza.com
    - title: Support
      href: mailto:apisupport@caliza.com
    - title: Security
      href: mailto:security@caliza.com  
  themeUrl: /assets/caliza-theme.css
  favicon: https://cdn.prod.website-files.com/677ed676bd7257ea423799b4/67a2a89e4980296d7851dd87_6430439ed754447dba330b58_caliza_favicon.png

