# Change these first
owner: caliza-financial # Your GitHub organization or username, where this repository lives
repo: caliza-status # The name of this repository

sites:
  - name: API
    url: https://api.caliza.com/core-api/actuator
  - name: Dashboard
    url: https://dashboard.caliza.com
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.caliza.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/Caliza-Financial/caliza-status/refs/heads/master/assets/caliza-dark-logo.svg
  name: Status Caliza
  introTitle: "Caliza system status"
  introMessage: >
    Public monitoring for the **API** and **Dashboard**. Data updates automatically every 5 minutes.
  navbar:
    - title: Status
      href: /
    - title: Incidents
      href: https://github.com/$OWNER/$REPO/issues
    - title: API Docs
      href: https://docs.caliza.com
    - title: Support
      href: mailto:apisupport@caliza.com
    - title: Security
      href: mailto:security@caliza.com
  theme: dark
  themeUrl: /assets/caliza-theme.css
  favicon: https://cdn.prod.website-files.com/677ed676bd7257ea423799b4/67a2a89e4980296d7851dd87_6430439ed754447dba330b58_caliza_favicon.png

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
